name: Deploy to GitHub Pages
# Run workflow on every push to the master branch
on:
  push:
    branches: [ master ]

jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with: 
        dotnet-version: '8.0.x'
    - run: dotnet publish AlbumRanking/AlbumRanking.csproj -c Release -o release --nologo
    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: master
        folder: release/wwwroot
    - name: Change base-tag in index.html
      run: sed -i 's/<base href="\/" \/>/<base href="\/AlbumRanking\/" \/>/g' release/wwwroot/index.html
    
